### ISSUE TITLE
Rewrite the program

### ISSUE THREAD

**Issue by ericdavidkelly** [ericdavidkelly/MP13#1]
The original program (written by Dave) was written in haste and has been very useful and appreciated.  However, it had some inefficiencies and simple approaches to misfit analysis.  I have improved the code in many ways but it has a long way to go to be truly efficient and precise.

A full rewrite, perhaps in Python, might be the best solution.  Maybe make extensions to run theriak (Fortran) directly.  theriak is rarely updated, so pulling in the code should be low effort in the long run.  Generally, it needs restructuring, especially toward reusable functions and subroutines.

Other reasons include the need for smarter/efficient input and output routines (or WUI/GUI), ability to display and edit graphics without third party software, and more help for the user in process flow (generate bulk comp from probe data, options for fractionation prior to PT path optimization, suggestions on what the results mean (or tutorials)).

**Comment by srmulcahy** [comment]
Hi Eric, I think moving this to Python would great and I may pair up with students in our computer science program to work on this.  Have you had any success running this on a Mac?
